services:
  - type: web
    name: medical-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PINECONE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
